sonar.projectKey=portoduque_SaaS-Skeleton
sonar.organization=portoduque
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.sources=apps/api/src/main/java,apps/web/src
sonar.tests=apps/api/src/test/java,apps/web/src
sonar.test.inclusions=apps/api/src/test/**/*.java,apps/web/src/**/*.test.ts,apps/web/src/**/*.test.tsx
sonar.exclusions=apps/web/src/**/*.test.ts,apps/web/src/**/*.test.tsx
sonar.coverage.exclusions=apps/api/src/main/java/dev/portoduque/saas/SaasSkeletonApplication.java

sonar.java.binaries=apps/api/target/classes
sonar.java.test.binaries=apps/api/target/test-classes
sonar.java.libraries=apps/api/target/dependency/*.jar
sonar.java.test.libraries=apps/api/target/dependency/*.jar
sonar.coverage.jacoco.xmlReportPaths=apps/api/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
