spring.application.name=saas-skeleton-api
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
